# Generated by Django 5.2.15 on 2026-09-09 00:51

import django.db.models.deletion
import shared.tenant
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0005_alter_business_cover_alter_business_logo_and_more'),
        ('tenants', '0002_alter_municipality_banner_alter_municipality_favicon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('video', models.FileField(upload_to=shared.tenant.TenantUploadTo('reels'), verbose_name='Video')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=shared.tenant.TenantUploadTo('reels/thumbnails'), verbose_name='Miniatura')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Duracion (seg)')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('inactive', 'Inactivo')], default='draft', max_length=10, verbose_name='Estado')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Me gusta')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='businesses.business')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='tenants.municipality')),
            ],
            options={
                'verbose_name': 'Reel',
                'verbose_name_plural': 'Reels',
                'ordering': ['-created_at'],
            },
        ),
    ]
