# Generated by Django 5.2.15 on 2026-09-09 00:51

import django.db.models.deletion
import shared.tenant
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0005_alter_business_cover_alter_business_logo_and_more'),
        ('tenants', '0002_alter_municipality_banner_alter_municipality_favicon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('event_type', models.CharField(choices=[('gastronomy', 'Gastronomia'), ('music', 'Musica'), ('cultural', 'Cultural'), ('sports', 'Deportes'), ('commercial', 'Comercial'), ('social', 'Social'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Tipo')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shared.tenant.TenantUploadTo('events'), verbose_name='Imagen')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Ubicacion')),
                ('start_date', models.DateTimeField(verbose_name='Inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fin')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad')),
                ('is_free', models.BooleanField(default=True, verbose_name='Gratuito')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
                ('ticket_url', models.URLField(blank=True, verbose_name='URL de Entradas')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('cancelled', 'Cancelado'), ('ended', 'Finalizado')], default='draft', max_length=10, verbose_name='Estado')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('business', models.ForeignKey(blank=True, help_text='Negocio que organiza el evento (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='businesses.business')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tenants.municipality')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-start_date'],
            },
        ),
    ]
