# Generated by Django 5.2.15 on 2026-09-09 00:51

import django.db.models.deletion
import shared.tenant
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0005_alter_business_cover_alter_business_logo_and_more'),
        ('tenants', '0002_alter_municipality_banner_alter_municipality_favicon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio')),
                ('category', models.CharField(choices=[('vehicles', 'Vehiculos'), ('real_estate', 'Inmuebles'), ('electronics', 'Electronica'), ('furniture', 'Muebles'), ('fashion', 'Moda'), ('services', 'Servicios'), ('animals', 'Mascotas'), ('jobs', 'Empleo'), ('other', 'Otro')], default='other', max_length=30, verbose_name='Categoria')),
                ('condition', models.CharField(choices=[('new', 'Nuevo'), ('used', 'Usado'), ('refurbished', 'Reacondicionado')], default='new', max_length=20, verbose_name='Condicion')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shared.tenant.TenantUploadTo('classifieds'), verbose_name='Imagen')),
                ('gallery', models.JSONField(blank=True, default=list, verbose_name='Galeria')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Ubicacion')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('sold', 'Vendido'), ('inactive', 'Inactivo')], default='draft', max_length=10, verbose_name='Estado')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifieds', to='businesses.business')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifieds', to='tenants.municipality')),
            ],
            options={
                'verbose_name': 'Clasificado',
                'verbose_name_plural': 'Clasificados',
                'ordering': ['-created_at'],
            },
        ),
    ]
