# Generated by Django 5.2.15 on 2026-07-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='Nombre Corto')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='businesses/logos/', verbose_name='Logo')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='businesses/covers/', verbose_name='Portada')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('history', models.TextField(blank=True, verbose_name='Historia')),
                ('mission', models.TextField(blank=True, verbose_name='Mision')),
                ('vision', models.TextField(blank=True, verbose_name='Vision')),
                ('values', models.TextField(blank=True, verbose_name='Valores')),
                ('address', models.TextField(verbose_name='Direccion')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Barrio')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='Codigo Postal')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('tiktok', models.URLField(blank=True, verbose_name='TikTok')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('pinterest', models.URLField(blank=True, verbose_name='Pinterest')),
                ('schedule', models.JSONField(default=dict, verbose_name='Horario')),
                ('features', models.JSONField(default=dict, verbose_name='Caracteristicas')),
                ('services', models.JSONField(default=dict, verbose_name='Servicios')),
                ('payment_methods', models.JSONField(default=dict, verbose_name='Metodos de Pago')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Verificacion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Aprobado')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobacion')),
                ('plan_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Vencimiento del Plan')),
                ('plan_auto_renew', models.BooleanField(default=False, verbose_name='Renovacion Automatica')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, max_length=300, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, verbose_name='Meta Keywords')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Visitas')),
                ('clicks_count', models.PositiveIntegerField(default=0, verbose_name='Clicks')),
                ('whatsapp_clicks', models.PositiveIntegerField(default=0, verbose_name='Clicks a WhatsApp')),
                ('call_clicks', models.PositiveIntegerField(default=0, verbose_name='Clicks a Llamada')),
                ('direction_clicks', models.PositiveIntegerField(default=0, verbose_name='Clicks a Direccion')),
                ('website_clicks', models.PositiveIntegerField(default=0, verbose_name='Clicks a Website')),
                ('social_clicks', models.PositiveIntegerField(default=0, verbose_name='Clicks a Redes Sociales')),
                ('favorite_count', models.PositiveIntegerField(default=0, verbose_name='Favoritos')),
                ('share_count', models.PositiveIntegerField(default=0, verbose_name='Compartidos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
            ],
            options={
                'verbose_name': 'Comercio',
                'verbose_name_plural': 'Comercios',
                'ordering': ['-views_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miercoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sabado'), ('sunday', 'Domingo')], max_length=10, verbose_name='Dia')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Apertura')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Cierre')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Cerrado')),
            ],
            options={
                'verbose_name': 'Horario del Comercio',
                'verbose_name_plural': 'Horarios del Comercio',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='BusinessMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video'), ('reel', 'Reel')], max_length=10, verbose_name='Tipo')),
                ('file', models.FileField(upload_to='businesses/media/%Y/%m/%d/', verbose_name='Archivo')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='businesses/thumbnails/', verbose_name='Miniatura')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Portada')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Visitas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
            ],
            options={
                'verbose_name': 'Media del Comercio',
                'verbose_name_plural': 'Medias del Comercio',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
