# Generated by Django 5.2.15 on 2026-07-02 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0003_initial'),
        ('categories', '0002_initial'),
        ('subscriptions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='subscriptions.plan'),
        ),
        migrations.AddField(
            model_name='business',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_businesses', to='categories.category'),
        ),
        migrations.AddField(
            model_name='business',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='businessmedia',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='businesses.business'),
        ),
        migrations.AlterUniqueTogether(
            name='businesshours',
            unique_together={('business', 'day')},
        ),
    ]
