# Generated by Django 5.2.15 on 2026-09-01 18:00

import shared.tenant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=shared.tenant.TenantUploadTo('businesses/covers'), verbose_name='Portada'),
        ),
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=shared.tenant.TenantUploadTo('businesses/logos'), verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='businessmedia',
            name='file',
            field=models.FileField(upload_to=shared.tenant.TenantUploadTo('businesses/media'), verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='businessmedia',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=shared.tenant.TenantUploadTo('businesses/thumbnails'), verbose_name='Miniatura'),
        ),
    ]
