version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.4
    container_name: rcl_db
    environment:
      POSTGRES_DB: rcl_db
      POSTGRES_USER: rcl_user
      POSTGRES_PASSWORD: rcl_password
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --locale=es_CO.UTF-8'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rcl_network

  redis:
    image: redis:7-alpine
    container_name: rcl_redis
    ports:
      - "6379:6379"
    networks:
      - rcl_network

  backend:
    build: .
    container_name: rcl_backend
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - RUN_INIT=1
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - rcl_network

  celery:
    build: .
    container_name: rcl_celery
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - rcl_network

  celery-beat:
    build: .
    container_name: rcl_celery_beat
    command: celery -A core beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - rcl_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  rcl_network:
    driver: bridge
