# Generated by Django 5.2.15 on 2026-09-15 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('scheduled', 'Programada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=10, verbose_name='Estado')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Solicitada')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha programada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de eliminacion de cuenta',
                'verbose_name_plural': 'Solicitudes de eliminacion de cuenta',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('profile', 'Datos de perfil'), ('location', 'Ubicacion'), ('push', 'Notificaciones push'), ('analytics', 'Analitica de uso'), ('ads', 'Publicidad personalizada')], max_length=20, verbose_name='Proposito')),
                ('granted', models.BooleanField(default=True, verbose_name='Otorgado')),
                ('consent_version', models.CharField(default='v1', max_length=20, verbose_name='Version')),
                ('mechanism', models.CharField(choices=[('first_run_consent_screen', 'Primer inicio - pantalla de consentimiento'), ('settings', 'Configuracion de privacidad'), ('revoke', 'Revocacion'), ('other', 'Otro')], default='other', max_length=50, verbose_name='Mecanismo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revocado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de consentimiento',
                'verbose_name_plural': 'Registros de consentimiento',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DataExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('ready', 'Listo'), ('failed', 'Fallido')], default='pending', max_length=10, verbose_name='Estado')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Solicitada')),
                ('file', models.FileField(blank=True, null=True, upload_to='exports/', verbose_name='Archivo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_export_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de exportacion',
                'verbose_name_plural': 'Solicitudes de exportacion',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='RightsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right', models.CharField(choices=[('access', 'Acceso'), ('rectification', 'Rectificacion'), ('erasure', 'Supresion'), ('restriction', 'Restriccion'), ('portability', 'Portabilidad'), ('objection', 'Oposicion')], max_length=20, verbose_name='Derecho')),
                ('details', models.TextField(blank=True, verbose_name='Detalles')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('done', 'Completado'), ('rejected', 'Rechazado')], default='pending', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rights_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Peticion de derechos',
                'verbose_name_plural': 'Peticiones de derechos',
                'ordering': ['-created_at'],
            },
        ),
    ]
