# Generated by Django 5.2.15 on 2026-09-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightsrequest',
            name='right',
            field=models.CharField(choices=[('Acceso', 'Acceso'), ('Corrección', 'Correccion'), ('Portabilidad', 'Portabilidad'), ('Oposición', 'Oposicion'), ('Limitación del tratamiento', 'Limitacion del tratamiento'), ('Eliminación', 'Eliminacion')], max_length=40, verbose_name='Derecho'),
        ),
    ]
