# Generated by Django 5.2.15 on 2026-07-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('icon', models.CharField(default='fa-store', max_length=50, verbose_name='Icono (FontAwesome)')),
                ('icon_color', models.CharField(default='#2563eb', max_length=7, verbose_name='Color del Icono')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacada')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['order', 'name'],
            },
        ),
    ]
