# Generated by Django 5.2.15 on 2026-09-01 18:00

import shared.tenant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shared.tenant.TenantUploadTo('categories'), verbose_name='Imagen'),
        ),
    ]
