# Generated by Django 5.2.15 on 2026-09-09 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0005_alter_business_cover_alter_business_logo_and_more'),
        ('tenants', '0002_alter_municipality_banner_alter_municipality_favicon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Puesto')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('requirements', models.TextField(blank=True, verbose_name='Requisitos')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sueldo Min')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sueldo Max')),
                ('job_type', models.CharField(choices=[('full_time', 'Tiempo completo'), ('part_time', 'Medio tiempo'), ('contract', 'Contrato'), ('internship', 'Pasantia'), ('freelance', 'Freelance'), ('temporary', 'Temporal')], default='full_time', max_length=20, verbose_name='Tipo')),
                ('work_mode', models.CharField(choices=[('onsite', 'Presencial'), ('remote', 'Remoto'), ('hybrid', 'Hibrido')], default='onsite', max_length=20, verbose_name='Modalidad')),
                ('application_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo de postulacion')),
                ('application_url', models.URLField(blank=True, verbose_name='URL de postulacion')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Ubicacion')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('closed', 'Cerrado')], default='draft', max_length=10, verbose_name='Estado')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
                ('applications_count', models.PositiveIntegerField(default=0, verbose_name='Postulaciones')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='businesses.business')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='tenants.municipality')),
            ],
            options={
                'verbose_name': 'Empleo',
                'verbose_name_plural': 'Empleos',
                'ordering': ['-created_at'],
            },
        ),
    ]
