# Generated by Django 5.2.15 on 2026-07-02 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('slogan', models.CharField(blank=True, max_length=200, verbose_name='Eslogan')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='tenants/favicons/', verbose_name='Favicon')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='tenants/banners/', verbose_name='Banner')),
                ('primary_color', models.CharField(default='#2563eb', max_length=7, verbose_name='Color Primario')),
                ('secondary_color', models.CharField(default='#7c3aed', max_length=7, verbose_name='Color Secundario')),
                ('accent_color', models.CharField(default='#f59e0b', max_length=7, verbose_name='Color de Acento')),
                ('background_color', models.CharField(default='#f3f4f6', max_length=7, verbose_name='Color de Fondo')),
                ('primary_font', models.CharField(default='Inter', max_length=100, verbose_name='Fuente Primaria')),
                ('secondary_font', models.CharField(default='Roboto', max_length=100, verbose_name='Fuente Secundaria')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('address', models.TextField(blank=True, verbose_name='Direccion')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('tiktok', models.URLField(blank=True, verbose_name='TikTok')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('timezone', models.CharField(default='America/Bogota', max_length=50, verbose_name='Zona Horaria')),
                ('config', models.JSONField(default=dict, verbose_name='Configuracion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_public', models.BooleanField(default=True, verbose_name='Publico')),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira Suscripcion')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Visitas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='municipalities', to='subscriptions.plan')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['name'],
            },
        ),
    ]
