# Generated by Django 5.2.15 on 2026-09-01 18:00

import shared.tenant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=shared.tenant.TenantUploadTo('banners'), verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=shared.tenant.TenantUploadTo('favicons'), verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=shared.tenant.TenantUploadTo('logos'), verbose_name='Logo'),
        ),
    ]
