# Generated by Django 5.2.15 on 2026-09-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_municipality_banner_alter_municipality_favicon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Configuracion'),
        ),
    ]
