# Generated by Django 5.2.15 on 2026-09-09 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotions', '0002_alter_promotion_image_alter_promotion_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Codigo')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('used', 'Usado'), ('expired', 'Expirado')], default='active', max_length=10, verbose_name='Estado')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True, verbose_name='Canjeado')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='promotions.promotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cupon',
                'verbose_name_plural': 'Cupones',
                'ordering': ['-created_at'],
            },
        ),
    ]
