# Generated by Django 5.2.15 on 2026-07-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('plan_type', models.CharField(choices=[('free', 'Gratuito'), ('basic', 'Basico'), ('entrepreneur', 'Emprendedor'), ('premium', 'Premium'), ('enterprise', 'Empresarial')], max_length=20, unique=True, verbose_name='Tipo')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
                ('currency', models.CharField(default='COP', max_length=3, verbose_name='Moneda')),
                ('price_period', models.CharField(choices=[('monthly', 'Mensual'), ('yearly', 'Anual'), ('lifetime', 'Vitalicio')], default='monthly', max_length=10, verbose_name='Periodo')),
                ('max_images', models.PositiveIntegerField(default=5, verbose_name='Max. Imagenes')),
                ('max_videos', models.PositiveIntegerField(default=0, verbose_name='Max. Videos')),
                ('max_reels', models.PositiveIntegerField(default=0, verbose_name='Max. Reels')),
                ('max_promotions', models.PositiveIntegerField(default=0, verbose_name='Max. Promociones')),
                ('max_products', models.PositiveIntegerField(default=0, verbose_name='Max. Productos')),
                ('max_employees', models.PositiveIntegerField(default=0, verbose_name='Max. Empleados')),
                ('has_analytics', models.BooleanField(default=False, verbose_name='Analitica')),
                ('has_promotions', models.BooleanField(default=False, verbose_name='Promociones')),
                ('has_reels', models.BooleanField(default=False, verbose_name='Reels')),
                ('has_videos', models.BooleanField(default=False, verbose_name='Videos')),
                ('has_geolocation', models.BooleanField(default=False, verbose_name='Geolocalizacion')),
                ('has_notifications', models.BooleanField(default=False, verbose_name='Notificaciones')),
                ('has_api_access', models.BooleanField(default=False, verbose_name='API Access')),
                ('has_advanced_analytics', models.BooleanField(default=False, verbose_name='Analitica Avanzada')),
                ('has_priority_support', models.BooleanField(default=False, verbose_name='Soporte Prioritario')),
                ('features', models.JSONField(default=dict, verbose_name='Caracteristicas')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de Fin')),
                ('renewal_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Renovacion')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Metodo de Pago')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia de Pago')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Pagado')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva'), ('expired', 'Expirada'), ('cancelled', 'Cancelada'), ('pending', 'Pendiente')], default='pending', max_length=10, verbose_name='Estado')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='Renovacion Automatica')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
            ],
            options={
                'verbose_name': 'Suscripcion',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
