# Generated by Django 5.2.15 on 2026-07-02 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Subtitulo')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/images/%Y/%m/%d/', verbose_name='Imagen')),
                ('video', models.FileField(blank=True, null=True, upload_to='promotions/videos/%Y/%m/%d/', verbose_name='Video')),
                ('gallery', models.JSONField(default=list, verbose_name='Galeria')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de Fin')),
                ('conditions', models.TextField(blank=True, verbose_name='Condiciones')),
                ('terms', models.TextField(blank=True, verbose_name='Terminos y Condiciones')),
                ('available_quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad Disponible')),
                ('used_quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad Usada')),
                ('max_per_user', models.PositiveIntegerField(default=1, verbose_name='Maximo por Usuario')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto Fijo'), ('bogo', '2x1'), ('free_shipping', 'Envio Gratis')], default='percentage', max_length=20, verbose_name='Tipo de Descuento')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor del Descuento')),
                ('min_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Compra Minima')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Descuento Maximo')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activa'), ('inactive', 'Inactiva'), ('expired', 'Expirada'), ('cancelled', 'Cancelada')], default='draft', max_length=10, verbose_name='Estado')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacada')),
                ('is_unlimited', models.BooleanField(default=False, verbose_name='Ilimitada')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
                ('redeemed_count', models.PositiveIntegerField(default=0, verbose_name='Canjeadas')),
                ('clicks_count', models.PositiveIntegerField(default=0, verbose_name='Clicks')),
                ('share_count', models.PositiveIntegerField(default=0, verbose_name='Compartidos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Promocion',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-created_at'],
            },
        ),
    ]
