# Generated by Django 5.2.15 on 2026-09-01 18:00

import shared.tenant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shared.tenant.TenantUploadTo('promotions/images'), verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=shared.tenant.TenantUploadTo('promotions/videos'), verbose_name='Video'),
        ),
    ]
