# Generated by Django 5.2.15 on 2026-07-02 00:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('global_admin', 'Administrador Global'), ('municipal_admin', 'Administrador Municipal'), ('merchant', 'Comerciante'), ('employee', 'Empleado'), ('moderator', 'Moderador'), ('user', 'Usuario'), ('tourist', 'Turista')], default='user', max_length=20, verbose_name='Rol')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='El telefono debe tener entre 9 y 15 digitos', regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefono')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='Avatar')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='users/covers/', verbose_name='Portada')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Codigo de Verificacion')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email Verificado')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='Telefono Verificado')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Biografia')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Ubicacion')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('P', 'Prefiero no decir')], max_length=10, verbose_name='Genero')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('notification_preferences', models.JSONField(default=dict, verbose_name='Preferencias de Notificacion')),
                ('language', models.CharField(default='es', max_length=10, verbose_name='Idioma')),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('system', 'Sistema')], default='system', max_length=10, verbose_name='Tema')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Ultimo Login')),
                ('last_login_device', models.CharField(blank=True, max_length=200, verbose_name='Dispositivo')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='2FA Activado')),
                ('two_factor_secret', models.CharField(blank=True, max_length=50, verbose_name='Secreto 2FA')),
                ('login_count', models.PositiveIntegerField(default=0, verbose_name='Conteo de Login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tenants.municipality')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
