# Generated by Django 5.2.15 on 2026-09-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar_alter_user_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict, verbose_name='Preferencias de Notificacion'),
        ),
    ]
