# Generated by Django 5.2.15 on 2026-09-09 00:51

import django.db.models.deletion
import shared.tenant
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0005_alter_business_cover_alter_business_logo_and_more'),
        ('tenants', '0002_alter_municipality_banner_alter_municipality_favicon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('ad_type', models.CharField(choices=[('banner', 'Banner'), ('inline', 'Inline'), ('video', 'Video')], default='banner', max_length=20, verbose_name='Tipo')),
                ('placement', models.CharField(choices=[('home', 'Inicio'), ('business', 'Comercios'), ('detail', 'Detalle de comercio'), ('promo_detail', 'Detalle de promocion')], default='home', max_length=30, verbose_name='Ubicacion')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shared.tenant.TenantUploadTo('ads'), verbose_name='Imagen')),
                ('video', models.FileField(blank=True, null=True, upload_to=shared.tenant.TenantUploadTo('ads/videos'), verbose_name='Video')),
                ('target_url', models.URLField(blank=True, verbose_name='URL de destino')),
                ('start_date', models.DateTimeField(verbose_name='Inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fin')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('paused', 'Pausado'), ('ended', 'Finalizado')], default='draft', max_length=10, verbose_name='Estado')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
                ('clicks_count', models.PositiveIntegerField(default=0, verbose_name='Clicks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='businesses.business')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='tenants.municipality')),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
                'ordering': ['-created_at'],
            },
        ),
    ]
