# Generated by Django 5.2.15 on 2026-09-13 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='rating',
            managers=[
            ],
        ),
    ]
