# Generated by Django 5.2.15 on 2026-09-09 00:51

import django.db.models.deletion
import shared.tenant
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_alter_municipality_banner_alter_municipality_favicon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('attraction_type', models.CharField(choices=[('natural', 'Natural'), ('historical', 'Historico'), ('cultural', 'Cultural'), ('adventure', 'Aventura'), ('recreational', 'Recreativo'), ('gastronomic', 'Gastronomico'), ('other', 'Otro')], default='natural', max_length=20, verbose_name='Tipo')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shared.tenant.TenantUploadTo('tourism'), verbose_name='Imagen')),
                ('gallery', models.JSONField(blank=True, default=list, verbose_name='Galeria')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Direccion')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Entrada')),
                ('is_free', models.BooleanField(default=False, verbose_name='Gratuito')),
                ('opening_hours', models.CharField(blank=True, max_length=200, verbose_name='Horario')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('inactive', 'Inactivo')], default='draft', max_length=10, verbose_name='Estado')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('is_top_rated', models.BooleanField(default=False, verbose_name='Mejor calificado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='tenants.municipality')),
            ],
            options={
                'verbose_name': 'Atraccion',
                'verbose_name_plural': 'Atracciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TouristRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shared.tenant.TenantUploadTo('tourism/routes'), verbose_name='Imagen')),
                ('duration_text', models.CharField(blank=True, max_length=100, verbose_name='Duracion')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacada')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('attractions', models.ManyToManyField(blank=True, related_name='routes', to='tourism.attraction')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourist_routes', to='tenants.municipality')),
            ],
            options={
                'verbose_name': 'Ruta Turistica',
                'verbose_name_plural': 'Rutas Turisticas',
            },
        ),
    ]
