# Generated by Django 5.2.15 on 2026-09-09 00:52

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0005_alter_business_cover_alter_business_logo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view', 'Visita'), ('click', 'Click'), ('claim', 'Canje'), ('share', 'Compartido'), ('favorite', 'Favorito')], max_length=20, verbose_name='Tipo')),
                ('source', models.CharField(blank=True, default='app', max_length=50, verbose_name='Fuente')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='businesses.business')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytic_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento analitico',
                'verbose_name_plural': 'Eventos analiticos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'event_type', 'created_at'], name='analytics_a_busines_2a271f_idx')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
