# Generated by Django 5.2.15 on 2026-09-09 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0005_alter_business_cover_alter_business_logo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('body', models.TextField(verbose_name='Mensaje')),
                ('notification_type', models.CharField(choices=[('info', 'Informacion'), ('promotion', 'Promocion'), ('order', 'Pedido'), ('message', 'Mensaje'), ('system', 'Sistema')], default='info', max_length=20, verbose_name='Tipo')),
                ('related_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID relacionado')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leida')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Datos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='businesses.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
